"""JSSP feasibility checker — standalone, no ML dependencies.

Parses a schedule string and checks five constraint categories:

    missing_op_count            : expected operations never emitted
    over_op_count               : more ops emitted for a job than expected
    routing_order_violations    : wrong machine or duration at routing position i
    machine_capacity_violations : two ops on the same machine overlap in time
    timing_consistency_violations: op where start + duration != end
    precedence_violations       : within a job, op[i] starts before op[i-1] ends

Schedule format expected (one op per token):
    J<job>-M<machine>: <start>+<duration>-><end>

Example:
    J0-M1: 0+3->3, J1-M0: 0+2->2
"""
import re

OP_PATTERN = re.compile(r'J(\d+)-M(\d+):\s*(\d+)\s*\+\s*(\d+)\s*->\s*(\d+)')


def extract_makespan(text: str):
    """Return the maximum end-time found in the schedule string, or None."""
    times = re.findall(r'->\s*(\d+)', text)
    return max(int(t) for t in times) if times else None


def parse_ops(text: str):
    """Parse schedule text into (valid_ops, timing_inconsistent_count).

    valid_ops : list of (job, machine, start, duration, end) where start+duration==end
    """
    valid, timing_bad = [], 0
    for m in OP_PATTERN.finditer(text):
        j, mc, s, d, e = map(int, m.groups())
        if s + d == e:
            valid.append((j, mc, s, d, e))
        else:
            timing_bad += 1
    return valid, timing_bad


def check_violations(schedule_str: str, jobs_spec: list) -> dict:
    """Check all JSSP constraints and return a result dictionary.

    Args:
        schedule_str : raw schedule text generated by the model
        jobs_spec    : list of jobs, each a list of (machine, duration) tuples
                       e.g. [[(1, 3), (0, 2)], [(0, 2), (1, 4)]] for a 2-job 2-machine problem

    Returns:
        dict with keys:
            feasible                        bool
            makespan                        int or None
            ops_emitted                     int
            ops_expected                    int
            missing_op_count                int
            over_op_count                   int
            routing_order_violations        int
            machine_capacity_violations     int
            timing_consistency_violations   int
            precedence_violations           int
            total_violations                int
    """
    valid_ops, timing_bad = parse_ops(schedule_str)

    n_jobs = len(jobs_spec)

    # Group valid ops by job
    by_job = {j: [] for j in range(n_jobs)}
    for op in valid_ops:
        if op[0] < n_jobs:
            by_job[op[0]].append(op)

    missing_op_count         = 0
    over_op_count            = 0
    routing_order_violations = 0
    precedence_violations    = 0

    for j, ops_j in by_job.items():
        ops_j.sort(key=lambda x: x[2])   # sort by start time
        expected = jobs_spec[j]
        n_exp    = len(expected)
        n_got    = len(ops_j)

        if n_got > n_exp:
            over_op_count += n_got - n_exp
        if n_got < n_exp:
            missing_op_count += n_exp - n_got

        last_end = 0
        for i, op in enumerate(ops_j[:n_exp]):
            req_machine, req_dur = expected[i]
            if op[1] != req_machine or op[3] != req_dur:
                routing_order_violations += 1
            if op[2] < last_end:
                precedence_violations += 1
            last_end = op[4]

    # Machine capacity: check for overlapping ops on the same machine
    by_machine = {}
    for op in valid_ops:
        by_machine.setdefault(op[1], []).append(op)

    machine_capacity_violations = 0
    for ops_m in by_machine.values():
        ops_m.sort(key=lambda x: x[2])
        for i in range(1, len(ops_m)):
            if ops_m[i][2] < ops_m[i - 1][4]:   # start < previous end
                machine_capacity_violations += 1

    total_expected = sum(len(j) for j in jobs_spec)

    feasible = (
        missing_op_count          == 0
        and over_op_count             == 0
        and routing_order_violations  == 0
        and machine_capacity_violations == 0
        and timing_bad                == 0
        and precedence_violations     == 0
    )

    total = (
        missing_op_count
        + over_op_count
        + routing_order_violations
        + machine_capacity_violations
        + timing_bad
        + precedence_violations
    )

    return {
        "feasible":                      feasible,
        "makespan":                      extract_makespan(schedule_str),
        "ops_emitted":                   len(valid_ops),
        "ops_expected":                  total_expected,
        "missing_op_count":              missing_op_count,
        "over_op_count":                 over_op_count,
        "routing_order_violations":      routing_order_violations,
        "machine_capacity_violations":   machine_capacity_violations,
        "timing_consistency_violations": timing_bad,
        "precedence_violations":         precedence_violations,
        "total_violations":              total,
    }
